### ISSUE TITLE
how to build on macos x86_64

### ISSUE THREAD

**Issue by hellok** [libtom/tomsfastmath#5]
1.
ifndef SIGCLD
   define SIGCLD SIGCHLD
endif
solved

2.src/mont/fp_montgomery_reduce.c:514:15: error: unknown register name '%cc' in
      asm
              INNERMUL8;

**Comment by sjaeckel** [comment]
I just tested the build on Mac OS X 10.12.4 and it works fine from current develop.

Latest release spits some warnings and makefile.shared was broken.

I'm closing this, as it's resolved.
